# Generated by Django 6.0.1 on 2026-01-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shelf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "permissions": [
                    ("can_create", "Can create shelf"),
                    ("can_delete", "Can delete shelf"),
                ],
            },
        ),
    ]
